# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'DDVP' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DDVP

  target 'DDVPTests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Bolts'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Core'

end
